{
   "anytime":[
      "Ich hoffe dein Tag ist so schön wie dein Gesicht!",
      "Ich bin glücklich, dein Spiegel zu sein!",
      "Auf einer Skala von 1 bis 10 bist du eine 15!",
      "Großartig zu sein ist schwer, aber du wirst es schaffen",
      "Ich könnte einfach den ganzen Tag hier hängen!",
      "Ich sehe viel von mir in dir",
      "Verdammt. Du siehst gut aus!",
      "Ja, du bist der Schönste von allen",
      "Möge die Macht mit dir sein",
      "Es gibt keinen Ort wie zu Hause",
      "Wenn Sie sich auf das konzentrieren, was Sie zurückgelassen haben, werden Sie nie sehen können, was vor Ihnen liegt",
      "*Ich trug eine Wassermelone*",
      "Ihr Händedruck vermittelt Intelligenz, Selbstvertrauen und leichte Unbeholfenheit",
      "Kakerlaken, Mäuse und andere Schädlinge meiden Ihren Platz aus Respekt",
      "Dein Lächeln ist ansteckend",
      "Du siehst heute großartig aus",
      "Du bist ein schlauer Keks",
      "Ich wette, du bringst Babys zum Lächeln",
      "Etwas verrückt - ist ganz nah an wundervoll",
      "Es gibt Tage - die man nie vergisst",
      "Aufgeben ist keine Option!",
      "Jeder sollte jemanden haben - bei dem man nicht normal sein muss",
      "Wer loslässt - hat die Hände frei für Neues",
      "Im nächsten Leben finde ich dich früher!",
      "Dein eigener Weg beginnt dort, wo du aufhörst, anderen zu folgen",
	  "Je mehr ich von den Menschen sehe - umso lieber habe ich meinen Hund",
      "Denken ist schwer - darum urteilen die meisten",
      "Richte deinen Fokus auf das Positive!",
      "Nimm dir Zeit für die Dinge, die dich glücklich machen",
      "Don't worry  -  be happy",
      "Der Clown ist die wichtigste Mahlzeit des Tages!",
      "Wenn ich dir jetzt recht gebe - dann liegen wir beide falsch",
      "Träume nicht dein Leben - sondern lebe deine Träume",
      "Sei glücklich & dankbar für das, was du hast",
	  "Ein Hund ist das Einzige Wesen auf Erden dass dich mehr liebt als sich selbst",
      "Warte nicht! Der Zeitpunkt wird niemals perfekt sein",
	  "Hunde haben Herrchen und Frauchen - Katzen haben Personal",
      "Einfach mal machen - Könnte ja gut werden",
      "Dankbarkeit ist der Schlüssel zur Schatzkammer unseres Lebens",
      "Jeder Mensch ist Kunst - gezeichnet vom Leben",
	  "Hunde kommen in unser Leben um zu bleiben",
      "Perfektion ist langweilig!",
      "Umso steiniger der Weg - umso wertvoller das Ziel!",
      "Hinfallen - aufstehen - Krone richten - weitermachen",
      "Du bist der schönste Zufall meines Lebens",
	  "Habe Achtung vor der Menschenkenntnis eines Hundes - er ist schneller und gründlicher",
      "Was du im Herzen trägst - kann dir niemand nehmen",
      "Glück ist wenn man dafür geliebt wird wie man eben ist",
      "Ich streite nicht - ich erkläre nur warum ich Recht habe",
      "Du bist wundervoll",
      "Heute werde ich die Welt erobern - mist es regnet",
      "Heute Lebe ich! Morgen putze ich.. Vielleicht",
      "Erinnere dich an gestern - denke an morgen - aber Lebe heute!",
      "Was früher meine Leber war - ist heute eine Minibar",
      "Was du heute kannst besorgen - das verschiebe nicht auf morgen",
      "Warum beleidigen - wenn ein Lächeln mehr provoziert",
      "*Das Leben ist wie eine Schachtel Pralinen ...*",
      "Ich liebe Kaktusblümchen",
      "Ohne Dich.. Kein Glück, keine Träume, keine Wünsche und keine Zukunft.",
      "Du bist meine Liebe und mein Herz! Du bist mein Glück! Du bist was ich mir wünsche! Marry me?",
      "Die kalte Schnauze eines Hundes ist erfreulich warm gegen die Kaltschnäuzigkeit mancher Menschen",
      "Be the person your dog thinks you are", 
      "Jobs füllen deine Brieftasche - Abenteuer deine Seele", 
      "Lass die Menschen gehen die deinen Wert nicht schätzen",
      "Wer ehrlich ist hat weniger Fans - kann aber besser schlafen",
      "Schminke kann man zu dick auftragen- Nutella nicht!", 
      "Jeder brauch einen sichere Ort - meiner bist Du!",
      "Genieße die kleinen Momente im Leben",
      "Steh jeden Tag auf & denke Positiv",
      "Habe Hoffnungen aber nie Erwartungen",
      "Wo es Liebe regnet - wünscht sich keiner einen Schirm",
      "Der Hund ist der sechste Sinn des Menschen", 
      "Hunde lügen nie - wenn es um Liebe geht",
      "Kein Psychiater kann es mit einem Hund aufnehmen - der übers Gesicht schleckt",
      "Ein Hund ist wie ein Herz auf Vier Pfoten",
      "Natürlich kann man ohne Hund leben - es lohnt sich nur nicht", 
      "Gib dem Menschen einen Hund & seine Seele wird gesund", 
      "Es gibt nur eins, was besser ist als ein Hund – zwei Hunde!",
      "Wer sagte, Glück könne man nicht kaufen, hat die kleinen Welpen vergessen",
      "Gute Menschen haben gute Hunde",
      "Hunde lieben ihre Freunde und beißen ihre Feinde",
      "Hunde glauben sie seien Menschen - Katzen glauben sie seien Gott",
      "Egal wie wenig Geld und Besitz du hast, einen Hund zu haben, macht dich reich",
      "Ein Hund der bellt - ist mehr wert - als ein Mensch der lügt",
      "Smile every day", 
      "Never give up",
      "Es wird nicht leichter - du wirst besser",
      "Lass dir dein Glitzern nicht nehmen",
      "Gib alles - nur nicht auf",
      "Today is a good day",
      "Wenn nicht jetzt - wann dann",
      "You are your only limit",
      "Dein lächeln steht dir gut",
      "An apple a day keeps the doctor away",
      "Everything is possible",
      "Mit dir kann ich Pferde stehlen",
      "Gegensätze ziehen sich an",
      "Wake up and be awesome",
      "*Liebe bedeutet, niemals um Verzeihung bitten zu müssen*",
      "*Mein Baby gehört zu mir*",
      "Carpe Diem",
	  "Du bist mein Zuhause",
      "Ein Tag mit dir ist mein Lieblingstag",
      "*Ich werd ihn Schwibbel-Schwabbel nennen und er wird mir gehören...*",
      "*Nicht jeder Schatz besteht aus Silber und Gold, weißt du.*",
      "*Nimm was du kriegen kannst! ? Und gib nichts wieder zurück.*",
      "*Es ist nicht gut, wenn wir nur unseren Träumen nachhängen und vergessen, zu leben.*",
      "*Viel mehr als unsere Fähigkeiten sind es unsere Entscheidungen, die zeigen, wer wir wirklich sind.*",
	  "*Wir wollen ihn! Wir brauchen ihn! Wir müssen ihn haben, den Schatz!*",
      "*Bibe di babe di Buh!*",
      "*Hakuna Matata. Das heißt.. Keine Sorgen.*",
      "*Manche Menschen sind es einfach wert, für sie zu schmelzen.*",
      "*Denn mit Gemütlichkeit kommt auch das Glück zu dir.*",
      "*Wer nichts Nettes zu sagen hat, soll den Mund halten.*",
      "Denn wenn ich dich ansehe, kann ich es fühlen. Ich sehe dich an und bin zu Hause.", 
	  "Du hast das schönste Lachen",
      "Du bist der Perfekteste, den es gibt",
      "Du bist ein großartiger Freund",
      "Du erstrahlst den Raum",
      "Du verdienst jetzt eine Umarmung",
      "Du solltest stolz auf dich sein",
      "Du bist hilfreicher als du denkst",
      "Sie haben einen großartigen Sinn für Humor",
      "Du bist das alles und eine super große Tüte Chips",
      "Du bist wie Sonnenschein an einem regnerischen Tag",
	  "Du bist ein großartiger Zuhörer",
      "Ich wette du schwitzt Glitzer",
      "In deiner Nähe zu sein macht alles besser!",
      "Farben scheinen heller zu sein, wenn DU in der Nähe sind",
      "Du bist wundervoll",
      "Du bist besser als eine Eistüte mit Streuseln",
      "Du bist einzigartig!",
      "Du inspirierst",
      "Jeder wird manchmal niedergeschlagen, aber man steht immer wieder auf und macht weiter",
      "Du bist eine Kerze in der Dunkelheit",
      "In deiner Nähe zu sein ist wie ein fröhlicher kleiner Urlaub"
   ],
   "morning":[
      "Guten Morgen Sonnenschein!",
      "Wer braucht Kaffee, wenn Sie Ihr Lächeln haben?",
      "Ich liebe den Geruch von Napalm am Morgen",
	  "Lass doch das Kissen im Bett",
      "Du bist heute früh dran",
      "Dein Haar ist mega heute!",
      "Beginne den Tag mit einem Lächeln",
	  "Der fühe Vogel fängt den Wurm"
      "Das wird ein schöner Tag!",
      "Heute wird großartig",
      "Carpe Diem"
   ],
   "afternoon":[
      "Mache noch schnell deine Arbeit fertig ...",
      "Nachmittag, nicht Morgen, nicht Mittag",
	  "Zeit für lecker Njam - Njam",
	  "Verwöhne dein Wau Wau",
      "Dieser Tag ist großartig",
      "Beinahe Abendessenszeit!"
   ],
   "evening":[
      "Du hast heute jemanden zum Lächeln gebracht, ich weiß es",
      "Der Tag war besser für Ihre Bemühungen",
	  "Zeit zu Schlemmen",
      "Bis morgen!",
      "Schlaf gut",
      "Guten Appetit",
      "Yeah, Freizeit",
      "War das Essen gut?"
   ],
   "snow":[
      "Schneeballschlacht!"
	  "Leise rieselt der Schnee",
	  "Baue einen Schneemann",
   ],
   "day_sunny":[
      "Heute ist ein sonniger Tag",
      "Sonne tanken",
	  "Time for a Dog Walk",
	  "Cora will spielen!",
      "Die Sonne scheint heute!",
	  "Have a wonderful Day",
      "Sunny Day Today",
      "Es ist wunderschön draußen, geh spielen!"
   ],
   "day_cloudy":[
      "Couch Time",
      "Es mag bewölkt sein, aber es ist immer noch schön draußen!",
      "Die Sonne versteckt sich gerade"
   ],
   "cloudy":[
      
   ],
   "cloudy_windy":[
      
   ],
   "showers":[
      
   ],
   "rain":[
      "Ein Regenschirm wäre nützlich",
      "Es ist nass da draußen, fahr vorsichtig!",
      "Draußen regnet es, aber du erhellst meinen Tag."
   ],
   "thunderstorm":[
	  "Eichen sollst du weichen - Buchen sollst du suchen",
   ],
   "fog":[
      
   ],
   "night_clear":[
      "Die Sterne funkeln"
	  "Sternschnuppen bringen Glück - Schau in den Himmel",
	  "Es gibt unzählige Sternbilder zu entdecken",
	  "LA Le LU  - Nur der Mann im Mond schaut zu",
   ],
   "night_cloudy":[
      
   ],
   "night_showers":[
      
   ],
   "night_rain":[
      
   ],
   "night_thunderstorm":[
      "Es ist eine stürmische Nacht, hab keine Angst"
   ],
   "night_alt_cloudy_windy":[
      
   ]
}
